package com.zo2ami.enums;

public enum ErrorCodes {
	
	MISSING_USERNAME("1000", "MISSING_USERNAME"),
	MISSING_EMAIL("1002", "MISSING_EMAIL"),
	MISSING_PASSWORD("1003", "MISSING_PASSWORD"),
	MISSING_CONFIRM_PASSWORD("1004", "MISSING_CONFIRM_PASSWORD"),
	MISSING_MOBILE_NUMBER("1005", "MISSING_MOBILE_NUMBER"),
	PASSWORDS_MISMATCH("1006", "PASSWORDS_MISMATCH"),
	MISSING_ACCOUNT_TYPE("1007", "MISSING_ACCOUNT_TYPE"),
	MISSING_CONTACT_PERSON_NAME("1008", "MISSING_CONTACT_PERSON_NAME"),
	MISSING_CONTACT_PERSON_EMAIL("1009", "MISSING_CONTACT_PERSON_EMAIL"),
	MISSING_CONTACT_PERSON_MOBILE_NUMBER("1010", "MISSING_CONTACT_PERSON_MOBILE_NUMBER"),
	MISSING_LOCATION("1011", "MISSING_LOCATION"),
	MISSING_LEGAL_DOCUMENT("1012", "MISSING_LEGAL_DOCUMENT"),
	USERNAME_ALREADY_EXIST("1013", "USERNAME_ALREADY_EXIST")
	;
	
	private final String code;
	private final String message;
	
	
	ErrorCodes(String code, String message){
		this.code = code;
		this.message = message;
	}


	public String getCode() {
		return code;
	}


	public String getMessage() {
		return message;
	}
	

}
