package com.zo2ami.enums;

public enum ErrorCodes {
	
	MISSING_USERNAME("1000", "MISSING_USERNAME"),
	MISSING_EMAIL("1002", "MISSING_EMAIL"),
	MISSING_PASSWORD("1003", "MISSING_PASSWORD"),
	MISSING_CONFIRM_PASSWORD("1004", "MISSING_CONFIRM_PASSWORD"),
	MISSING_MOBILE_NUMBER("1005", "MISSING_MOBILE_NUMBER"),
	PASSWORDS_MISMATCH("1006", "PASSWORDS_MISMATCH"),
	MISSING_ACCOUNT_TYPE("1007", "MISSING_ACCOUNT_TYPE"),
	MISSING_CONTACT_PERSON_NAME("1008", "MISSING_CONTACT_PERSON_NAME"),
	MISSING_CONTACT_PERSON_EMAIL("1009", "MISSING_CONTACT_PERSON_EMAIL"),
	MISSING_CONTACT_PERSON_MOBILE_NUMBER("1010", "MISSING_CONTACT_PERSON_MOBILE_NUMBER"),
	MISSING_LOCATION("1011", "MISSING_LOCATION"),
	MISSING_LEGAL_DOCUMENT("1012", "MISSING_LEGAL_DOCUMENT"),
	USERNAME_ALREADY_EXISTS("1013", "USERNAME_ALREADY_EXISTS"),
	USER_NOT_FOUND("1014", "USER_NOT_FOUND"),
	MISSING_RESET_PASSWORD_TOKEN("1015", "MISSING_RESET_PASSWORD_TOKEN"),
	INVALID_RESET_PASSWORD_TOKEN("1016", "INVALID_RESET_PASSWORD_TOKEN"),
	PASSWORDS_NOT_MATCHED("1017", "PASSWORDS_NOT_MATCHED"),
	PASSWORD_ALREADY_CHANGED("1018", "PASSWORD_ALREADY_CHANGED"),
	MISSING_CLIENT_TYPE("1019", "MISSING_CLIENT_TYPE"),
	EMAIL_ALREADY_EXISTS("1020", "EMAIL_ALREADY_EXISTS"),
	;
	
	private final String code;
	private final String message;
	
	
	ErrorCodes(String code, String message){
		this.code = code;
		this.message = message;
	}


	public String getCode() {
		return code;
	}


	public String getMessage() {
		return message;
	}
	

}
